version: '3.8'

services:
  app:
    build: .
    container_name: coupon-app
    expose:
      - "8080" # 只給內部 nginx 存取
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=couponuser
      - DB_PASSWORD=couponpass
      - DB_NAME=coupons
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:latest
    container_name: coupon-nginx
    ports:
      - "8082:80" # 對外改為 8082
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupons
      MYSQL_USER: couponuser
      MYSQL_PASSWORD: couponpass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: coupon-redis
    ports:
      - "6380:6379"

volumes:
  mysql_data: